### ISSUE TITLE
Crashing on specific type of installation

### ISSUE THREAD

**Issue by JanSpulak** [stefboerrigter/wavinsentio-ha#2]
I obtain the LOG from HASS, where installed MODBUS access. I don't know what is happend. This data taken from "SCHOOL" I will ask for more information.

[home-assistant_2024-03-09T21-28-19.842Z.log](https://github.com/stefboerrigter/wavinsentio-ha/files/14558885/home-assistant_2024-03-09T21-28-19.842Z.log)

**Comment by stefboerrigterWavin** [comment]
Issue seems to be caused by reading of RoomPreset from value which is not in enum:
```
class SentioRoomPreset(Enum):
    RP_INVALID = -1
    RP_ECO= 0
    RP_COMFORT = 1
    RP_EXTRA_COMFORT = 2
```
Can you read out the room presets and see if there are more (unsupported) types?

**Comment by stefboerrigterWavin** [comment]
Found it and fixed in modbus library. please test with updated revision

**Comment by stefboerrigter** [comment]
please check with updated version @JanSpulak
