### ISSUE TITLE
Some Constants are missing

### ISSUE THREAD

**Issue by JanSpulak** [stefboerrigter/wavinsentio-ha#6]
Hello, 

I have tried a new release, but I have seen the some errors in log>
![image](https://github.com/stefboerrigter/wavinsentio-ha/assets/31966916/f7db6db0-34a5-40f5-a110-44fa2414d8cf)

The constant ClimateEntityFeature.TURN_OFF , etc not found in the context. And next Endian.BIG is missing too.

@stefboerrigter It's looks like that some file not pushed correctly or missing.

**Comment by stefboerrigterWavin** [comment]
@JanSpulak which version of home-assistant are you using?
